### ISSUE TITLE
ids-cdp.txt missing

### ISSUE THREAD

**Issue by cwittern** [kawabata/ids-edit#4]
Kawabata-san,

The ids-edit package on melpa ist broken.  The package pulls a file called "ids.txt", but in the repo and in the code, the file is called ids-cdp.txt.  Please update.

Chris

**Comment by kawabata** [comment]
I'm sorry to miss this message.
Problem should have been fixed and it now supports Extension-F (Unicode 10) as well.
Please install HanaMin AFDKO font (temporalily placed at 
https://github.com/kawabata/glyphwiki-afdko/releases) to use this tool.
